[package]
name = "zero2prod2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.5.11"
serde = { version = "1.0.138", features = ["derive"] }
tokio = { version = "1.19.2", features = ["rt-multi-thread", "macros"] }

[dev-dependencies]
reqwest = "0.11.11"
